### ISSUE TITLE
Incorrect new mail count 

### ISSUE THREAD

**Issue by osmoossi** [rockfield/owa_firefox_addon#3]
Thanks for the great addon for Firefox! 

The latest version of the addon works great for me, except the count of new mails is wrong. It seems to be two or three times the right count. The toast notification also shows incorrect count. I have no new mails in other folders. Screenshot is attached.

My setup:
Linux Mint 17.1 (Ubuntu 14.04 LTS based)
Firefox 34.0
Outlooks Web App Notifications 1.2.2

![firefox](https://cloud.githubusercontent.com/assets/9627024/5311899/29d0f8e8-7c58-11e4-97fd-16fc759d1aa0.png)

Please let me know if you need any more information!

**Comment by phalox** [comment]
Could the initial request be promoted to a feature request?

I've traced it down to: https://github.com/rockfield/owa_firefox_addon/blob/master/data/icon_notifications.js#L109

I guess the aria labels are for the 2013 client?

Maybe it's possible to add an option which folders to monitor. This would include looping over all <span id="spnTrNdCnt"></span> entries, check if the name in the underlying span spnFldrNm is the same and add code.

I could do the jscript, but I don't know how firefox's options work just yet.

**Comment by rockfield** [comment]
I'm going to add option to monitor only Inbox section in Favorites (it accumulates inboxes from different accounts).

I believe we can't rely on classes or IDs because in different / future versions it can be changed (but it's only my opinion :)

If you make JS script and I will help you to bring it with Firefox setting section.=

**Comment by osmoossi** [comment]
Adding option to only monitor Inbox is a great feature.
But the original issue I am having is not caused by this. The wrong count also comes when I have no new mail in other folders. When I recieve a new email, the popup seems to always have double the amount.

**Comment by phalox** [comment]
Did you check your favorite folders? It might be collapsed, but the code will be there anyway.

I'll see when I can mock something together. I was looking at whether there is some support of an array type in firefox preferences, but I don't see anything.

So, either we just monitor ALL folders, or just one (the unread one?). If we still want to monitor multiple ones, we probably need some form of separation and parse them.

**Comment by osmoossi** [comment]
Ah didn't notice Favorites since it was collapsed. Sorry my bad.
So looks like the issue will be fixed by just monitoring the Inbox.

**Comment by phalox** [comment]
Well actually monitoring the unread emails is better. This one contains just the new emails. While it's possible to make rules that move your mails immediately to other folders, resulting in them not being in the inbox anymore.

**Comment by osmoossi** [comment]
That is true. As long as those aren't showed twice :+1:

**Comment by phalox** [comment]
Ok, this is probably the shittiest code fix ever, but I have no way of testing it so I could only copy it here...


function countUnreadMessages() {
    var unreadContainer;
    var count = 0;
    var folder_panes = document.querySelectorAll("[aria-label='Folder Pane']");
    if (folder_panes.length > 0) {
        for(var pane = folder_panes.length-1; pane >= 0; pane--){
            unreadContainer = folder_panes[pane].querySelectorAll("[id*='.ucount']");
            count = countIt(unreadContainer);
        }
    } else {
        unreadContainer = document.querySelectorAll('#spnCV');
        var subSetunreadContainer = [];
        for(var u_node = unreadContainer.length-1; u_node>=0; u_node--) {
            var container = unreadContainer[u_node];
            var folderName = container.parentNode.parentNode.querySelector('#spnFldrNm').getAttribute("fldrnm");
            
            // Can be used to check for other folder names also
            if(folderName == "Unread Mail") {
                subSetunreadContainer.push(container);
            }
        }
        count = countIt(subSetunreadContainer);
    }
    return count;
}

**Comment by rockfield** [comment]
New note:
tab notifier has been changed by @mihai-chezan and now shows the number of unread messages, but pop-up info as far as I understand still shows the number of NEW unread messages.

**Comment by phalox** [comment]
Ticket can be closed. Confirmed working
