### ISSUE TITLE
Don't match Draft/Junk Messages

### ISSUE THREAD

**Issue by tbraeutigam** [rockfield/owa_firefox_addon#5]
Currently the addon seems to match draft and unread messages.

The following should fix this (countIT function, line 93 of the file):

Original Code:
```javascript
 count += parseInt(unreadContainer[u_node].innerHTML.match(/\d/gi).join(""), 10);
```

With Fix:
```javascript
 count += parseInt(unreadContainer[u_node].innerHTML.match(/\d{1,} unread/gi).join(""), 10);
```

OWA writes '1 unread', etc for emails in most folders, but for Drafts and Junk it shows '1 item', etc.

Kind Regards,

Thorben

**Comment by rockfield** [comment]
Where is it?
![unread](https://cloud.githubusercontent.com/assets/1464331/6043211/c1674a9a-ac9b-11e4-915a-f2570166134d.png)

**Comment by tbraeutigam** [comment]
Hi,

The code matches in the span with .ucount in it, which is two below the one you opened. - This seems to happen in line 103 of `data/icon_notifications.js`.

This is at least the case for OWA 2013 -- I don't have OWA 2010 to test it with right now.

Kind Regards,

Thorben

**Comment by rockfield** [comment]
Hi there again :)
Yeah, you're right and you're cool, thanks :)

I'will include this fix in update.

**Comment by rockfield** [comment]
I've known, I have 2015 year version.
Anyway, I've included and built extension with your patch which I rewrote a little.
I've checked — it works.
Can you check this?

**Comment by phalox** [comment]
I'm thinking this broke support for the 2010 version entirely. There is no such field in there.
Could you revert it back and split up the functions so that support is kept for older version ?

Thanks

**Comment by rockfield** [comment]
Yeah, ofc

**Comment by rockfield** [comment]
I've kept your RegExp:
```javascript
.match(/\d{1,} unread/gi)
```
instead of original:
```javascript
.match(/\d/gi)
```

**Comment by rockfield** [comment]
I just was forced to expand this line:
```javascript
count += parseInt(unreadContainer[u_node].innerHTML.match(/\d{1,} unread/gi).join(""), 10);
```
into
```javascript
var amountArr = unreadContainer[u_node].innerHTML.match(/\d{1,} unread/gi);
if ( Array.isArray(amountArr) ) {
	count += parseInt(amountArr[0], 10);
}
```
because in some cases it brakes run-time: this is just syntax construction and nothing more.

**Comment by rockfield** [comment]
The same time I don't have 2010 version I trust you that your fixes will work.

**Comment by phalox** [comment]
Which fixes are you referring to?
I did not submit the ".match(/\d{1,} unread/gi)"
This is the line that now breaks the 2010 support. it no longer matches any mails. It used to work with the .match(/\d/gi)

**Comment by phalox** [comment]
For the 2010 version, we're looking for all the #spnCV elements, these look like
  <span id="spnCV">1</span>
surely, only the \d will match here.
The subSetunreadContainer variable will only contain references to these elements.

Since this is your tool, I don't know what you prefer better. To keep the countit functon work for all version, or to split up the entire functionality for 2010<->other version?

I don't have the tools here now to debug this one.

**Comment by rockfield** [comment]
@phalox, sorry, I've been answering to @tbraeutigam.
I got it, thanks. Already fixed and uploded to marketplace.

**Comment by phalox** [comment]
Support for 2010 fixed, thanks!
Also incorrect count is now ok for 2010.

**Comment by rockfield** [comment]
Glad to know :+1:
