### ISSUE TITLE
Detects unread "Deleted Items"

### ISSUE THREAD

**Issue by ghost** [rockfield/owa_firefox_addon#7]
Emails that haven't been read but are sent to the Deleted Items folder (Junk emails for example) are treated the same as new emails in the Inbox.

Also, is it possible to add a toolbar button? This would help when we're away from the PC and miss the popup.

**Comment by PhilippBaranovskiy** [comment]
Actually it would be better to repost this wish to community hub: https://github.com/owa-web/owa_firefox_addon

Also another idea to catch your unread emails is "pin a tab" so OWA tab with unread counter will be always visible.
Actually I think it would be better to add just toolbar-button-counter without needed to keep open owa tab but it's another request and another feature.

I will repost your wish.
